### ISSUE TITLE
Missing opcode for C_SELECT_CHANNEL

### ISSUE THREAD

**Issue by devnull0x00** [tera-toolbox/tera-data#24]
For NA, v88.4, protocol 359881 for use with channel-command module.

**Comment by Tera-Shiraneko** [comment]
Isn't supported and therefore won't be added.

**Comment by devnull0x00** [comment]
Not supported as in by proxy or as in opcode was removed entirely and is thus not available?

**Comment by Tera-Shiraneko** [comment]
I think it was never added to begin with for reasons.

**Comment by devnull0x00** [comment]
Curious as to what those reasons would be. In any event, how to pull opcodes? (and before you ask, yes, I am an engineer).

**Comment by KYGAS** [comment]
It isn't supported since it can be used for bad stuff, it does exist. You can get an opcode by logging packets and comparing the data with the definitions and seeing if they could match, basically trial and error, after some time, it will get easier.

**Comment by devnull0x00** [comment]
Yeah I know  to log the packets, but, what tool?

**Comment by KYGAS** [comment]
You are best off making your own, but there are some public ones as well. "Alex packet logger" or something, google it.
